### ISSUE TITLE
zxp installed into wrong folder

### ISSUE THREAD

**Issue by FlorianLudwig** [GreyRook/Draw2Script#5]
The zxp might end up installing Draw2Script into the wrong folder on Windows.

Needs investigation.

**Comment by mikebarkmin** [comment]
Extension Manager has been discontinued. The lastest release will only work with Adobe CC 2014. When you own Adobe CC 2015 you must install Draw2Script manually. See Announcement: Extension Manager End of Life Notification https://s3.amazonaws.com/cssdk/2015-05-22_TechPartners.html
