### ISSUE TITLE
Export as SVG

### ISSUE THREAD

**Issue by FlorianLudwig** [GreyRook/Draw2Script#9]
It seems useful to be able to export to SVG as it allows exporting parts of an image as suggested by @tripl3inf here: https://github.com/tomkrcha/drawscript/issues/11#issuecomment-66940571

**Comment by jgraup** [comment]
I just read [Tips for Creating and Exporting Better SVGs for the Web](http://sarasoueidan.com/blog/svg-tips-for-designers/) and [Useful SVGO[ptimization] Tools](http://sarasoueidan.com/blog/svgo-tools/). I don't think you need to go as far as [SVGO GUI](https://github.com/jakearchibald/svgomg) ([demo](https://jakearchibald.github.io/svgomg/)), but it might be nice to have a minimal amount of optimizations applied like [SVG-NOW](https://github.com/davidderaedt/SVG-NOW).

**Comment by jordandobson** [comment]
I would love to have paths returned... much like this: http://jrdn.io/image/1v0S0I041L2E That way I can add them quickly into my prototypes and HTML files... or create sprites quickly and easily.

**Comment by FlorianLudwig** [comment]
Currently there is no plan to implement this. Closing.
